---
title: "Thesis R"
---

```{r}
library(tidyverse)
library(manifestoR)
library(quanteda)
library(quanteda.textstats)
library(quanteda.textplots)
library(jsonlite)
```

```{r}
secrets <- read_json("./../../secrets.txt")

mp_setapikey(key = secrets$ManifestoAPI)

my_df <- mp_corpus(countryname == "Bosnia-Herzegovina", as_tibble = TRUE)
my_corp <- mp_corpus(countryname == "Bosnia-Herzegovina")

corp <- corpus(my_corp, text_field = "text")

docvars(my_corp)

content(my_corp[["79321_200210"]])

mp_view_originals(party == 79321 & date == 200210)

```



```{r}
doc <- my_corp[["79321_200210"]]
docCodes <- codes(doc) %>% 
  tibble() %>% rename(codes = 1) %>% 
  filter(!duplicated(codes))

mp_describe_code("602.1")
```


```{r}
df <- readRDS("BiH_02-07_term_final.RDS") %>% 
  mutate(date = ymd(date),
         date = str_replace_all(date, "3013-", "2013-"),
         date_raw = str_replace_all(date_raw, ".3013", ".2013")) %>% 
  filter(date >= ymd("2010-01-01"))

sum <- df %>% 
  summarise(dateRange = paste0(first(term1), "-", last(term1)))

turk <- df %>% 
  filter(str_detect(lem, "[Tt]urska|[Tt]urc"))

rus <- df %>% 
  filter(str_detect(lem, "[Rr]usija|[Rr]uski"))

write_csv(df, "parliment_debates_BA.csv")

```

